### ISSUE TITLE
Support the OpenFeature Provider

### ISSUE THREAD

**Issue by shanman190** [openrewrite/rewrite-feature-flags#6]
https://openfeature.dev/

LaunchDarkly has a provider interface that can be used behind OpenFeature. This issue is to track and see if adding such support would be desired by the community.

**Comment by timtebeek** [comment]
Had a very brief look at the docs: https://openfeature.dev/docs/reference/technologies/server/java#usage

With the new-ish `methodPattern` argument to `RemoveBoolVariation` it should be trivial to now also support OpenFeature's `Client getBooleanValue(String, boolean)`
https://github.com/openrewrite/rewrite-launchdarkly/blob/b053c8ae509fa8c7c5bdbe8104d6b03d38d05da3/src/main/java/org/openrewrite/launchdarkly/RemoveBoolVariation.java#L64-L70

Might be nice to add as an explicit recipe, in an appropriate openfeature package in this repository, such that it's easier to find for folks.
